name: Lint and Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install, tests
        run: |
          make install
          make test
      - name: lint
        run: make lint